Web/Controllers/ArticleController.cs
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class ArticleController:BaseController<Article,ArticleViewModel>
    {
        public ArticleController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/ArticlesCategoryController.cs
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class ArticlesCategoryController : BaseController<ArticlesCategory, ArticlesCategoryViewModel>
    {
        public ArticlesCategoryController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/CategoriesGamesController.cs
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class CategoriesGamesController : BaseController<CategoriesGames, CategoriesGamesViewModel>
    {
        public CategoriesGamesController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class ContactUsController : BaseController<ContactUs, ContactUsViewModel>
    {
        public ContactUsController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/FormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using Web.Models;
using WebExtensions.Events;

namespace Web.Controllers
{
    public class FormSurfaceController : SurfaceController
    {
        private readonly IEventPublisher _eventPublisher;
      

        public FormSurfaceController(IEventPublisher eventPublisher)
        {
            _eventPublisher = eventPublisher;
        }


        public ActionResult ContactForm()
        {
            //if (TempData["Success"] != null && (bool)TempData["Success"])
            //{
            //    return SuccessMessage();
            //}
            var model = (ContactFormModel)TempData["FaultyModel"] ?? new ContactFormModel();
            return PartialView("_ContactForm", model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SubmitContactForm(ContactFormModel model)
        {
            if (ModelState.IsValid)
            {
                model.EmailTo = CurrentPage.GetPropertyValue<string>("emailTo", true);
                model.EmailSubject = "פניה חדשה מטופס צור קשר";
                _eventPublisher.Publish(new Event<ContactFormModel> { Entity = model });
                return Success(model);
            }

            return Error(model);
        }

        public ActionResult Error(BaseContactFormModel model)
        {
            TempData["FaultyModel"] = model;
            return CurrentUmbracoPage();
        }

        private ActionResult Success(BaseContactFormModel model)
        {
            TempData["Success"] = true;
            var thanksPage = CurrentPage.Children(x => x.DocumentTypeAlias == "ThankYouPage").FirstOrDefault();
            return RedirectToUmbracoPage(thanksPage);
        }

        //private ActionResult SuccessMessage()
        //{
        //    TempData.Remove("Success");
        //    return PartialView("_SuccessMessage", CurrentPage.GetPropertyValue<string>("successMessage"));
        //}
    }
}

Web/Controllers/GalleryCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class GalleryCategoryController : BaseController<GalleryCategory,GalleryCategoryViewModel>
    {
       
        public GalleryCategoryController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class GalleryController : BaseController<Gallery,GalleryViewModel>
    {
       

        public GalleryController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
        

    }
}

Web/Controllers/GameController.cs
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class GameController : BaseController<Game, GameViewModel>
    {

        public GameController(IMapperProvider mapperProvider)
            : base(mapperProvider)
        {
        }

       

    }
}

Web/Controllers/HomepageController.cs
using System.Web.Mvc;
using Examine;
using Umbraco.Web;
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.Services;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class HomepageController : BaseController<HomePage,HomePageViewModel>
    {
        private readonly IExternalSearchService _externalSearchService;

        public HomepageController(IMapperProvider mapperProvider, IExternalSearchService externalSearchService)
            : base(mapperProvider)
        {
            _externalSearchService = externalSearchService;
        }

        public ActionResult SearchResults(string searchTerm)
        {
            ISearchResults results = null;
            if (searchTerm.Length >= 3)
                results = _externalSearchService.Search(searchTerm, CurrentPage.AncestorOrSelf(1).Id);
            var vm = CreateSearchResultsModel(results, searchTerm);

            return View(vm);
        }

        private SearchResultsViewModel CreateSearchResultsModel(ISearchResults results, string q)
        {

            var model = CurrentPage.MapContent<SearchResults, SearchResultsViewModel>(_mapperProvider);
            model.Header.Name = "תוצאות חיפוש";
            model.Results = results;
            if (results == null)
            {
                model.Message = "יש להקיש לפחות 3 תווים על מנת לבצע חיפוש";
            }
            else if (results.TotalItemCount == 0)
            {
                model.Message = string.Format("לא נמצאו תוצאות לחיפוש \"{0}\"", q);

            }
            else
            {
                model.Message = string.Format("נמצאו {0} תוצאות ל \"{1}\"", results.TotalItemCount, q);
            }

            return model;
        }

    }
}

Web/Controllers/MovieController.cs
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class MovieController : BaseController<Movie,MovieViewModel>
    {
        public MovieController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/NewsCategoryController.cs
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class NewsCategoryController : BaseController<NewsCategory,NewsCategoryViewModel>
    {
        public NewsCategoryController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/NewsController.cs
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class NewsController : BaseController<News,NewsViewModel>
    {
        public NewsController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/SubCategoryGamesController.cs
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class SubCategoryGamesController : BaseController<SubCategoryGames, SubCategoryGamesViewModel>
    {
        public SubCategoryGamesController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Controllers/ThankYouPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebExtensions.Common;
using WebExtensions.Domain;
using WebExtensions.MVC;
using WebExtensions.ViewModels;

namespace Web.Controllers
{
    public class ThankYouPageController : BaseController<ThankYouPage, ThankYouPageViewModel>
    {
        public ThankYouPageController(IMapperProvider mapperProvider) : base(mapperProvider)
        {
        }
    }
}

Web/Views/Article.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.ArticleViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
}
<div class="row">
    @if(!Model.HideSideMenu)
    {
        <div class="col-md-2 side-menu">
            @Html.CachedPartial("_SideNav", Model.SideNav, 5, true)
        </div>
    }
    <div class="@(!Model.HideSideMenu ? "col-md-10" : "col-md-12")">
    @if (!Model.HideTitle)
    {
            <h1 class="red">@Model.Name</h1>
        }
            <article>
                @Html.Raw(Model.PageBody)
            </article>
        </div>
    </div>

Web/Views/ArticlesCategory.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.ArticlesCategoryViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";

    var firstArticle = Model.Articles.Where(x => x.IsVisible).OrderByDescending(x => x.CreateDate).First();
    var otherArticles = Model.Articles.Where(x => x.IsVisible).OrderByDescending(x => x.CreateDate).Skip(1).ToList();
}

<section class="articles">
    @if (!Model.HideTitle)
    {
        <h1 class="red">@Model.Name</h1>
    }
    <div class="row">
        <div class="col-md-12">
            @Html.Raw(Model.PageBody)
        </div>   
    </div>
    @if (firstArticle != null)
    {
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="no-padding">
                    <img src="@firstArticle.ArticleImageWide" alt="@firstArticle.Name" class="img-responsive" />
                    <div class="article-content">
                        <div class="pull-left">@firstArticle.CreateDate.ToString("dd/MM/yyyy")</div>
                        <h3>@firstArticle.Name</h3>
                        <div>@firstArticle.ShortText</div>
                        <div>
                            <a href="@firstArticle.Url">לקריאת המאמר</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    <div class="row">
        <div class="col-md-12">
            @if (otherArticles.Any())
            {
                <ul class="list-inline">
                    @foreach (var article in otherArticles)
                    {
                        <li>
                            <div class="box">
                                <img src="@article.ArticleImageUrl" alt="@article.Name" class="img-responsive" />
                                <div class="article-content">
                                    <div class="pull-left">@article.CreateDate.ToString("dd/MM/yyyy")</div>
                                    <h4>@article.Name</h4>
                                    <div>@(article.ShortText.Length > 250 ? article.ShortText.Substring(0, 250) + "..." : article.ShortText)</div>
                                    <div>
                                        <a href="@article.Url">לקריאת המאמר</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }
                </ul>
            }
        </div>
    </div>
</section>

Web/Views/CategoriesGames.cshtml
@using Umbraco.Web
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.CategoriesGamesViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
    var listWidth = 180*Model.SubCategoryGames.Count + "px";
}
@if (!Model.HideTitle)
{
    <h1 class="green">@Model.Name</h1>
}
<div class="text-cat">
    @Html.Raw(Model.PageBody)
</div>
<ul class="category-list clearfix" style="width:@listWidth">
    @foreach (var item in Model.SubCategoryGames.Where(x=>x.IsVisible))
    {
        <li>
            <figure>
                <a href="@item.Url">
                    <img src="@item.ImageUrl?width=137&height=74&mode=crop" alt="@item.Name" />
                </a>
                <figcaption><a href="@item.Url">@item.Name</a></figcaption>
            </figure>
        </li>
    }
</ul>
<div class="row">
    <div class="col-md-11 col-md-offset-1"><h2 class="MostNews">המשחקים הכי חדשים</h2></div>
    <div class="col-md-12">
        <ul class="category-list news">
            @foreach (var item in Model.LastGames)
            {
                <li>
                    <figure>
                        <a href="@item.Url">
                            <img src="@item.SmallImageUrl" alt="@item.Name" />
                        </a>
                        <figcaption><a href="@item.Url">@item.Name</a></figcaption>
                    </figure>
                </li>
            }
        </ul>

    </div>
</div>

Web/Views/CategoriesMovies.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.CategoriesMoviesViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
    var listWidth = 180 * Model.SubCategoryMovies.Count + "px";
}
@if (!Model.HideTitle)
{
    <h1 class="purple">@Model.Name</h1>
}
<div class="text-cat">
    @Html.Raw(Model.PageBody)
</div>

<ul class="category-list clearfix" style="width:@listWidth">
    @foreach (var item in Model.SubCategoryMovies.Where(x=>x.IsVisible))
    {
        <li>
            <figure>
                <a href="@item.Url">
                    <img src="@item.ImageUrl?width=137&height=74&mode=crop" alt="@item.Name" />
                </a>
                <figcaption><a href="@item.Url">@item.Name</a></figcaption>
            </figure>
        </li>
    }
</ul>
<div class="row">
    <div class="col-md-11 col-md-offset-1"><h2 class="MostNews">סירטונים הכי חדשים</h2></div>
    <div class="col-md-12">
        <ul class="category-list">
            @foreach (var item in Model.LastMovies)
            {
                <li>
                    <figure>
                        <a href="@item.YouTubeUrl" data-type="iframe" class="fancybox">
                            <img src="@item.SmallImageUrl" alt="@item.Name" />
                        </a>
                        <figcaption>@item.Name</figcaption>
                    </figure>
                </li>
            }
        </ul>
    </div>
</div>

Web/Views/ContactUs.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.ContactUsViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
}
<h1 class="blue">@Model.Name</h1>
<div class="col-md-12">
    <div class="row">
        @Html.Action("ContactForm", "FormSurface")
    </div>
</div>

Web/Views/Gallery.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.GalleryViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
}@if (!Model.HideTitle)
 {
     <h1 class="pink">@Model.Name</h1>
 }
<div class="col-md-12">
    <div id="grid-gallery" class="grid-gallery">
        <section class="grid-wrap">
            <ul class="grid">
                @*<li class="grid-sizer"></li>*@
                @foreach (var image in Model.Media)
                {
                    <li>
                        <figure>
                            <img src="@image.ImageUrl" alt="@image.ImageName" />
                            @*<figcaption><h3>@image.ImageName</h3></figcaption>*@
                        </figure>
                    </li>
                }
            </ul>
        </section>
        <section class="slideshow">
            <ul>
                @foreach (var image in Model.Media)
                {
                    <li>
                        <figure>
                            <img src="@image.ImageUrl" alt="@image.ImageName" />
                        </figure>
                    </li>
                }
            </ul>
            <nav>
                <span class="icon nav-prev"></span>
                <span class="icon nav-next"></span>
                <span class="icon nav-close"></span>
            </nav>
          
        </section>

    </div>
</div>
@section scripts
{
    @*@Scripts.Render("~/scripts/grid-gallery")*@
    @Scripts.Render("~/scripts/grid-gallery/imagesloaded.pkgd.min.js", "~/scripts/grid-gallery/masonry.pkgd.min.js", "~/scripts/grid-gallery/classie.js", "~/scripts/grid-gallery/cbpGridGallery.js"
)
    <script>
        new CBPGridGallery(document.getElementById('grid-gallery'));
    </script>
}
@section head
{
    @*@Styles.Render("~/css/grid-gallery")*@
    @Styles.Render("~/css/grid-gallery/component.css", "~/css/grid-gallery/demo.css")
    @Scripts.Render("~/scripts/grid-gallery/modernizr.custom.js")
}

Web/Views/GalleryCategory.cshtml
@using WebExtensions.PropertyEditorTypes
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.GalleryCategoryViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
    var listWidth = 180 * Model.Galleries.Count + "px";
    var galleries = Model.Galleries.Select(x => x.Media);
    var lastMadia = new List<MediaFolderFeature>();
    galleries.ForEach(x =>
    {
        x.ForEach(lastMadia.Add);
    });
    
}
@if (!Model.HideTitle)
{
    <h1 class="pink">@Model.Name</h1>
}
<div class="text-cat">
    @Html.Raw(Model.PageBody)
</div>
<ul class="category-list clearfix" style="width:@listWidth">
    @foreach (var item in @Model.Galleries.Where(x=>x.IsVisible))
    {
        <li>
            <figure>
                <a href="@item.Url">
                    <img src="@item.ImageUrl?width=137&height=74&mode=crop" alt="@item.Name">
                    <figcaption>
                        @item.Name
                    </figcaption>
                </a>
            </figure>
        </li>
    }
</ul>
<div class="row">
    <div class="col-md-11 col-md-offset-1"><h2 class="MostNews">התמונות הכי חדשות</h2></div>
    @Html.CachedPartial("_NewMedia", lastMadia.OrderByDescending(x=>x.Id).Take(10).ToList(),5,true)
</div>
@section scripts
{
    @*@Scripts.Render("~/scripts/grid-gallery")*@
    @Scripts.Render("~/scripts/grid-gallery/imagesloaded.pkgd.min.js", "~/scripts/grid-gallery/masonry.pkgd.min.js", "~/scripts/grid-gallery/classie.js", "~/scripts/grid-gallery/cbpGridGallery.js"
)
    <script>
        new CBPGridGallery(document.getElementById('grid-gallery'));
    </script>
}
@section head
{
    @*@Styles.Render("~/css/grid-gallery")*@
    @Styles.Render("~/css/grid-gallery/component.css", "~/css/grid-gallery/demo.css")
    @Scripts.Render("~/scripts/grid-gallery/modernizr.custom.js")
}

Web/Views/HomePage.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.HomePageViewModel>
@{
    Layout = "Shared/_Layout.cshtml";
}
<div class="row main-content">
    <div class="col-sm-9">
        <div class="row">
            <div class="col-sm-4">
                <div class="image1">
                    @if (!string.IsNullOrWhiteSpace(Model.Images[0].ImageLink))
                    {
                        @*<figure>*@
                        <a href="@Model.Images[0].ImageLink">
                            @*@Model.Images[0].ImageUrl data-type="image" class="fancybox"*@
                            <img src="@Model.Images[0].ImageUrl?width=173&height=241&mode=crop" alt="@Model.Images[0].ImageTitle" class="imgresponsive" />
                        </a>
                        @*<figcaption><a href="@Model.Images[0].ImageLink">@Model.Images[0].ImageTitle</a></figcaption>
                            </figure>*@
                    }
                    else
                    {
                        <img src="@Model.Images[0].ImageUrl?width=173&height=241&mode=crop" alt="@Model.Images[0].ImageTitle" class="imgresponsive" />
                    }
                </div>
            </div>
            <div class="col-sm-8">
                <div class="newsList">
                    <div class="title">
                        <img src="/images/title_news.png" class="img-responsive" />
                    </div>
                    <ul class="side-menu-news">
                        @foreach (var item in Model.NewsPicker)
                        {

                            <li @(Model.NewsPicker[0] == item ? "class=active" : string.Empty) data-tab="@(Model.NewsPicker.IndexOf(item))">@item.Name</li>
                        }
                    </ul>
                    <div class="newsItemPic">
                        <div class="overlay"></div>
                        <ul class="news-pic">
                            @foreach (var item in Model.NewsPicker)
                            {
                                <li @(Model.NewsPicker[0] == item ? "class=newsImage" : string.Empty) data-image="@(Model.NewsPicker.IndexOf(item))">
                                    <a href="@item.Url"><img src="@item.HomeImageUrl" alt="@item.Name" /></a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <article class="hp-text">
                    @Html.Raw(Model.PageBody)
                </article>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 row-divider"></div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <div class="title-clips">
                    <img src="/images/title_klips.png" alt="" class="img-responsive" />
                    <ul class="clip-list">
                        @foreach (var item in Model.ClipsPicker)
                        {
                            <li>
                                <figure>
                                    <a href="@item.YouTubeUrl" data-type="iframe" class="fancybox">
                                        <img src="@item.SmallImageUrl" alt="@item.Name" />
                                    </a>
                                    <a href="@item.YouTubeUrl" data-type="iframe" class="fancybox">
                                        <figcaption>@item.Name</figcaption>
                                    </a>
                                </figure>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="title-pics">
                    <img src="/images/title_pics.png" alt="" class="img-responsive" />
                    <ul class="pic-list">
                        @foreach (var image in Model.MediaPicker)
                        {
                            <li>
                                <figure>
                                    <a href="@image.ImageUrl" data-type="image" class="fancybox">
                                        <img src="@image.ImageUrl?width=118&height=68&mode=crop" alt="@image.ImageTitle" />
                                    </a>
                                    <a href="@image.ImageUrl" data-type="image" class="fancybox">
                                        <figcaption>@image.ImageTitle</figcaption>
                                    </a>
                                </figure>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <div class="col-sm-3">

                <div class="title-movies">
                    <img src="/images/title_movies.png" alt="" class="img-responsive" />
                </div>
                <ul class="pic-list">
                    @foreach (var item in Model.MoviesPicker)
                    {
                        <li>
                            <figure>
                                <a href="@item.YouTubeUrl" data-type="iframe" class="fancybox">
                                    <img src="@item.SmallImageUrl" alt="@item.Name" />
                                </a>
                                <a href="@item.YouTubeUrl" data-type="iframe" class="fancybox">
                                    <figcaption>@item.Name</figcaption>
                                </a>

                            </figure>
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 row-divider"></div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="title"><img src="/images/title_games.png" alt="" class="img-responsive" /></div>
                <ul class="row game-list">
                    @foreach (var item in Model.GamesPicker)
                    {
                        <li class="col-sm-6">
                            <a href="@item.Url">
                                <figure>
                                    <img src="@item.SmallImageUrl" alt="@item.Name" />
                                    <figcaption>@item.Name</figcaption>
                                </figure>
                            </a>
                        </li>
                    }
                </ul>
            </div>
            <div class="col-sm-6">
                @if (!string.IsNullOrWhiteSpace(Model.Images[2].ImageLink))
                {
                    @*<figure class="image2">*@
                    <a href="@Model.Images[2].ImageLink">
                        <img src="@Model.Images[2].ImageUrl?width=372&height=210&mode=crop" class="imgresponsive" />
                    </a>
                    @*<figcaption><a href="@Model.Images[2].ImageLink">@Model.Images[2].ImageTitle</a></figcaption>
                        </figure>*@
                }
                else
                {
                    <img src="@Model.Images[2].ImageUrl?width=372&height=210&mode=crop" class="imgresponsive" />
                }
            </div>
        </div>
    </div>
    <div class="col-sm-3">
        @if (!string.IsNullOrWhiteSpace(Model.Images[1].ImageLink))
        {
            @*<figure class="image3">*@
            <a href="@Model.Images[1].ImageLink">
                <img src="@Model.Images[1].ImageUrl?width=240&height =98&mode =crop" class="imgresponsive" />
            </a>
            @*<figcaption><a href="@Model.Images[1].ImageLink">@Model.Images[1].ImageTitle</a></figcaption>
                </figure>*@
        }
        else
        {
            <img src="@Model.Images[1].ImageUrl?width=240&height =98&mode =crop" class="imgresponsive" />
        }
        <!--banner-->
        <figure class="banner-side">
            <img src="/images/banner_side.png" class="imgresponsive" />
        </figure>

        <!--facebook like box-->
        @if (!string.IsNullOrWhiteSpace(Model.Header.FacebookLink))
        {
            <div class="fb-like-box" data-href="@Model.Header.FacebookLink" data-width="262" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>
        }
        </div>
    </div>
@section scripts
{
    <script>
            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
}

Web/Views/Movie.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.MovieViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
}

Web/Views/News.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.NewsViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
    ViewBag.Title = "newsItem";
}
<div class="row">
    @if (!Model.HideSideMenu)
    {
        <div class="col-md-2 side-menu">
            @Html.CachedPartial("_SideNav", Model.SideNav, 5, true)
        </div>
    }
    <div class="@(!Model.HideSideMenu?"col-md-10":"col-md-12")">
        @if (!Model.HideTitle)
        {
            <h1 class="orange">@Model.Name</h1>
        }
        <article>
            <img src="@Model.LargeImageUrl" alt="@Model.Name" class="img-responsive f-left img-thumbnail" />
            @Html.Raw(Model.PageBody)
        </article>
    </div>
</div>

Web/Views/NewsCategory.cshtml
@inherits WebExtensions.MVC.WebLayout<WebExtensions.ViewModels.NewsCategoryViewModel>
@{
    Layout = "Shared/_InnerLayout.cshtml";
}
@if (!Model.HideTitle)
{
    <h1 class="orange">@Model.Name</h1>
}
<ul class="category-list">
    @foreach (var item in Model.News)
    {
        <li>
            <figure>
                <img src="@item.SmallImageUrl" alt="@item.Name" />
                <figcaption><a href="@item.Url">@item.Name</a></figcaption>
            </figure>
        </li>
    }
</ul>